# Generated by Django 5.2.3 on 2025-07-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='guest_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
