# Generated by Django 5.2.3 on 2025-07-04 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_role_alter_session_guest_session_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'timestamp'], name='chat_messag_session_a7a43a_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'is_guest_session'], name='chat_sessio_user_id_9a4bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['guest_session_id', 'is_guest_session'], name='chat_sessio_guest_s_1c0a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['-updated_at'], name='chat_sessio_updated_d473f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('is_guest_session', False), models.Q(('is_guest_session', True), ('user__isnull', True), ('guest_session_id__isnull', False)), _connector='OR'), name='guest_session_constraint'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('is_guest_session', True), models.Q(('is_guest_session', False), ('user__isnull', False), ('guest_session_id__isnull', True)), _connector='OR'), name='user_session_constraint'),
        ),
    ]
