# Generated by Django 5.2.3 on 2025-07-04 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_chat_messag_session_a7a43a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session',
            name='guest_session_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='session',
            name='user_session_constraint',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='session_timestamp_idx',
            old_name='chat_messag_session_a7a43a_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='user_session_idx',
            old_name='chat_sessio_user_id_9a4bb7_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='guest_session_idx',
            old_name='chat_sessio_guest_s_1c0a1c_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='session_updated_idx',
            old_name='chat_sessio_updated_d473f5_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'role'], name='session_role_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', '-updated_at'], name='user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['guest_session_id', '-updated_at'], name='guest_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('is_guest_session', False), models.Q(('is_guest_session', True), ('user__isnull', True), ('guest_session_id__isnull', False)), _connector='OR'), name='strict_guest_session_constraint'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('is_guest_session', True), models.Q(('is_guest_session', False), ('user__isnull', False), ('guest_session_id__isnull', True)), _connector='OR'), name='strict_user_session_constraint'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', True), ('guest_session_id__isnull', True), _connector='OR'), name='no_mixed_session_constraint'),
        ),
    ]
