# Generated by Django 5.2.3 on 2025-07-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_session_guest_session_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session',
            name='strict_guest_session_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='session',
            name='strict_user_session_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='session',
            name='no_mixed_session_constraint',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='session_timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='session_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='user_session_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='guest_session_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='session_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='user_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='guest_updated_idx',
        ),
    ]
